const makeItems = (values) => values.map((value) => {
  const [title, description] = value.split('|');
  return { title, description };
});

const eo = {
  nav: { home: 'Komenco', events: 'Eventoj', services: 'Servoj', artists: 'Artistoj', gallery: 'Galerio', contact: 'Kontakto', tickets: 'Biletoj', openMenu: 'Malfermi menuon', language: 'Elekti lingvon' },
  hero: { line1: 'Kie elektronika muziko', line2: '', gradient: 'Vibras kun vi', desktopLine1: 'Kie elektronika muziko', desktopLine2: 'Vibras kun vi', description: 'Elektronikaj eventoj, aŭdvida produktado, booking kaj undergroundaj spertoj el Tarragona kaj Barcelono.', nextEvent: 'Vidi venontan eventon', hireServices: 'Dungi servojn', joinNewsletter: 'Aliĝi al la novaĵletero', scroll: 'Iri al la venonta evento' },
  next: { stamp1: 'Venonta', stamp2: 'evento', eyebrow: 'Venonta dato', buy: 'Aĉeti biletojn', countdown: 'Retronombrado', countdownLabel: 'Restanta tempo ĝis la evento', units: { days: 'Tagoj', hours: 'Horoj', minutes: 'Minutoj', seconds: 'Sekundoj' } },
  parties: { eyebrow: 'Eventoj · Identeco', title: 'Niaj', accent: 'festoj', description: 'Kvar universoj. Unu maniero kompreni la dancejon.', brand: 'Marko de LICAN', discover: 'Malkovri', descriptions: { FERAL: 'Hard Techno, Schranz, Raw kaj Industrial. Malluma, fizika kaj rita sperto.', 'Headbang Dealers': 'Dubstep, Riddim, Tearout kaj Drum and Bass. Bass-kulturo kaj regata kaoso.', 'Night Of Series': 'Elektronika diverseco, UV, glow kaj esprimlibereco.', NOVA: 'Nuntempa elektronika muziko, kulturo kaj alirebla formato por novaj publikoj.' } },
  memory: { eyebrow: 'Memoro LICAN', title: 'Realigitaj', accent: 'eventoj' },
  realized: { eyebrow: 'Memoro LICAN', title: 'Realigitaj', accent: 'eventoj', description: 'Afiŝoj kaj memoroj pri la datoj, kiuj konstruis la universon LICAN.', filterLabel: 'Filtri realigitajn eventojn laŭ marko', filters: { all: 'Ĉiuj', feral: 'FERAL', 'headbang-dealers': 'Headbang Dealers', 'night-of-wolves': 'Night Of Wolves', nova: 'NOVA', lican: 'LICAN' }, descriptionTemplates: { feral: '{title} estas parto de la sagao FERAL: hard techno, industria sono kaj forta rita identeco.', 'headbang-dealers': '{title} alportis bass-kulturon, dubstep kaj headbang-energion al la undergrounda komunumo.', 'night-of-wolves': '{title} kunigis alternativan elektronikan muzikon, glow-estetikon kaj la komunuman spiriton de Night Of Wolves.', nova: '{title} kunligis nuntempan elektronikan muzikon, kulturon kaj alireblan formaton por novaj publikoj.', lican: '{title} kunigis lokan kulturon, kreivan produktadon kaj elektronikan muzikon sub LICAN EVENTS.' } },
  business: { eyebrow: 'B2B · Produktado', lead1: 'Ni organizas', lead2: 'vian eventon', accent: 'laŭmezure', description: 'Produktado, DJ-oj, sono, vidaĵoj, aŭdvida enhavo, biletado, kampanjoj kaj teknika kunordigo.', services: 'Vidi servojn', quote: 'Peti buĝeton' },
  services: { eyebrow: 'B2B · Produktado', title: 'Profesiaj', accent: 'servoj', description: 'Plena produktado, komunikado kaj tekniko por krei laŭmezurajn spertojn.', quote: 'Peti buĝeton', info: 'Informoj', items: makeItems(['Plena produktado|Koncepto, planado kaj kompleta kunordigo.', 'Merkatado|Strategio, kampanjoj kaj komunikado.', 'Vidaĵoj|VJing, aŭdvida enhavo kaj surscenigo.', 'Sono|Projektado kaj kunordigo de sonsistemoj.', 'Lumigado|Lumdezajno kaj atmosferoj.', 'Fotografio|Profesia kovrado kaj vida memoro.', 'Video|Aftermovies kaj aŭdvidaj pecoj.', 'Booking|Elekto kaj dungado de artistoj.', 'Sponsoradoj|Kunligo inter markoj, kulturo kaj publiko.', 'Eventoj por markoj|Laŭmezuraj spertoj por kompanioj.']) },
  artists: { eyebrow: 'DJ-oj · Produktantoj · Artistoj', title: 'Servoj por', accent: 'artistoj, DJ-oj kaj produktantoj', description: 'Fotolibro, presskit, registrado de setoj, aŭdvida enhavo, vidaĵoj, reklamado kaj profesia subteno por via projekto.', cta: 'Mi volas labori kun LICAN', items: makeItems(['Fotolibro|Profesia artista bildaro.', 'Presskit|Biografio, fotoj, rider kaj ligiloj.', 'Registrado de setoj|Video kaj sono de prezentadoj.', 'Aŭdvida enhavo|Pecoj por prezenti vian projekton.', 'Vivaj vidaĵoj|Enhavo sinkronigita kun via muziko.', 'Reklamado|Komunikado kaj cifereca ĉeesto.', 'Booking|Subteno por trovi scenejojn.', 'Profesia subteno|Gvidado kaj kontaktoj en la sektoro.']) },
  gallery: { eyebrow: 'Vida memoro', title: 'Galerio', photos: 'fotoj' },
  collaborators: { eyebrow: 'Fido', title: 'Kunlaborantoj', accent: 'kaj ejoj' },
  partners: { title: 'Interkonsentoj kaj kunlaborantaj', accent: 'markoj', ariaLabel: 'Interkonsentoj kaj kunlaborantaj markoj de LICAN EVENTS' },
  newsletter: { eyebrow: 'Komunumo LICAN', title1: 'Aliĝu al la', title2: 'novaĵletero', description: 'Ricevu niajn venontajn eventojn, ofertojn kaj novaĵojn de LICAN.', send: 'Sendi', sending: 'Sendante...', subscribed: 'Aliĝinta', consent: 'Mi konsentas ricevi komunikojn de LICAN EVENTS pri eventoj, ofertoj kaj novaĵoj. Mi povas malaliĝi iam ajn.', invalidEmail: 'Enigu validan retpoŝtadreson.', consentError: 'Vi devas akcepti la komunikojn por aliĝi.', submitError: 'Ne eblis sendi. Bonvolu reprovi.', success: 'Vi aliĝis. Ni informos vin pri venontaj datoj.' },
  contact: { eyebrow: 'Ni parolu', title: 'Kontaktu', accent: 'LICAN EVENTS', description: 'Biletoj, servoj, artistoj, sponsoradoj aŭ kunlaboroj. Ni estas ĉi tie.', location: 'Loko', name: 'Nomo', namePlaceholder: 'Via nomo', queryType: 'Tipo de demando', select: 'Elektu...', message: 'Mesaĝo', messagePlaceholder: 'Rakontu al ni, kiel ni povas helpi...', consent: 'Mi konsentas, ke LICAN EVENTS prilaboru miajn datumojn por respondi ĉi tiun demandon.', send: 'Sendi mesaĝon', sending: 'Sendante...', sent: 'Sendita', success: 'Mesaĝo sukcese sendita. Ni respondos kiel eble plej baldaŭ.', submitError: 'Ne eblis sendi. Reprovu aŭ skribu al info@licanevents.com.', errors: { name: 'Enigu vian nomon.', email: 'Enigu vian retpoŝtadreson.', invalidEmail: 'Enigu validan retpoŝtadreson.', type: 'Elektu tipon de demando.', message: 'Skribu vian mesaĝon.', consent: 'Vi devas akcepti la privatecan politikon.' }, inquiries: ['Biletoj', 'Dungi servojn', 'Artistoj / DJ-oj', 'Sponsoradoj', 'Kunlaboroj', 'Gazetaro', 'Alia'] },
  common: { toBeConfirmed: 'Konfirmota' },
  footer: { description: 'Organizanto kaj kultura produktanto de undergrounda elektronika muziko.', navigation: 'Navigado', contact: 'Kontakto' },
  pages: {
    events: { h1: 'Festoj LICAN', h1Lines: [{ base: 'Festoj', accent: 'LICAN' }], intro: 'Malkovru niajn markojn, venontajn eventojn kaj la memoron de jam okazintaj datoj.', title: 'Eventoj', description: 'Elektronikaj eventoj kaj festoj de LICAN EVENTS en Tarragona kaj Barcelono.' },
    services: { h1: 'Profesiaj servoj', h1Lines: [{ base: 'Profesiaj', accent: 'servoj' }], intro: 'Plena produktado, komunikado kaj tekniko por krei laŭmezurajn spertojn.', title: 'Profesiaj servoj', description: 'Profesiaj servoj por eventoj.' },
    artists: { h1: 'Servoj por artistoj, DJ-oj kaj produktantoj', h1Lines: [{ base: 'Servoj por' }, { accent: 'artistoj, DJ-oj' }, { base: 'produktantoj' }], intro: 'Bildo, enhavo, reklamado kaj profesia subteno por progresigi vian projekton.', title: 'Servoj por artistoj', description: 'Servoj por artistoj kaj DJ-oj.' },
    gallery: { h1: 'Galerio', intro: 'Elekto de niaj noktoj, artistoj, vidaĵoj kaj publiko.', title: 'Galerio', description: 'Fotoj de eventoj de LICAN EVENTS.' },
    contact: { h1: 'Kontaktu LICAN EVENTS', intro: 'Rakontu al ni, kion vi volas krei.', title: 'Kontakto', description: 'Kontaktu LICAN EVENTS en Tarragona kaj Barcelono.' },
  },
  contactCta: { eyebrow: 'Ni parolu', general: { title: 'Ĉu vi volas organizi ion kun LICAN?', description: 'Biletoj, servoj, artistoj, sponsoradoj aŭ kunlaboroj. Skribu al ni kaj ni konkretigos ĝin.' }, artist: { title: 'Sendu al ni vian projekton', description: 'Rakontu al ni pri vi kaj via projekto.' }, contact: 'Kontakti' },
};

export default eo;
