// TODO(legal): Confirm legal entity/name, tax ID, postal address, processor
// contracts, transfer safeguards and actual retention periods with LICAN.
// Do not replace these omissions with invented company data.
export const legalCopy = {
  cast: {
    notice: 'Información del sitio en revisión: los datos identificativos completos del responsable y los plazos legales de conservación están pendientes de confirmación. Puedes solicitar información en info@licanevents.com.',
    cookies: [
      ['Qué son las cookies', 'Son pequeños archivos que un sitio guarda en el navegador. También utilizamos almacenamiento local para recordar preferencias y funciones solicitadas.'],
      ['Tipos que utiliza LICAN EVENTS', 'Distinguimos funciones necesarias, analítica opcional y marketing. Marketing está desactivado y no se carga ninguna herramienta publicitaria. Rechazar es tan sencillo como aceptar.'],
      ['Necesarias', 'La elección de cookies se guarda en lican_cookie_consent; el idioma se recuerda en lican-language. El juego puede guardar progreso local y datos de sesión si utilizas una cuenta. Estos datos funcionales no dependen de aceptar analíticas.'],
      ['Analíticas y Google Analytics', 'Solo tras aceptar analíticas se carga Google Analytics 4 (G-C2SPKSH8HJ), proveedor Google. Mide páginas visitadas, navegación y datos técnicos de uso. No enviamos nombres, correos ni mensajes de formularios mediante el tracker. Consulta también la política de privacidad de Google.'],
      ['Cookies e inventario', 'Verificadas tras aceptar: _ga (distingue visitantes) y _ga_C2SPKSH8HJ (estado de sesión de Analytics). Su caducidad observada en Edge fue de unos 400 días; puede variar según navegador y configuración. No se crean antes de aceptar; las accesibles se eliminan al retirar el permiso.'],
      ['Duración', 'La elección de consentimiento se recuerda hasta 180 días, salvo borrado previo o cambio de versión. El almacenamiento local no caduca por sí solo; el sitio comprueba su antigüedad al cargar. El idioma y el progreso local permanecen hasta que se cambien o borren. Los plazos de conservación configurados en Google Analytics están pendientes de confirmación.'],
      ['Cambiar o retirar el permiso', 'Abre PREFERENCIAS DE COOKIES en el pie de página. Puedes retirar analíticas en cualquier momento. Se bloquean nuevos eventos del tracker y se eliminan las cookies de Analytics accesibles para este sitio. Retirar el permiso no altera la licitud del tratamiento anterior.'],
      ['Configuración del navegador', 'Puedes consultar, bloquear o eliminar cookies y datos del sitio desde los ajustes de privacidad de tu navegador. Borrar datos puede eliminar el idioma, el consentimiento o el progreso local del juego.'],
      ['Contacto', 'LICAN EVENTS · Tarragona y Barcelona. Consultas: info@licanevents.com.'],
    ],
    privacy: [
      ['Responsable', 'Este sitio se presenta como LICAN EVENTS, con actividad en Tarragona y Barcelona y contacto info@licanevents.com. La identidad jurídica completa y el domicilio del responsable están pendientes de confirmación.'],
      ['Finalidades y base jurídica', 'Gestionamos consultas y solicitudes de servicios para atender tu petición y, cuando proceda, actuaciones precontractuales. El envío de la newsletter requiere tu consentimiento específico. La analítica web requiere una elección voluntaria separada; rechazarla no impide usar formularios, newsletter o juegos.'],
      ['Datos tratados', 'El formulario de contacto solicita nombre, email, tipo de consulta, mensaje y confirmación de privacidad. La newsletter solicita email y consentimiento. Si utilizas una cuenta del juego, se tratan los datos de autenticación y las funciones de guardado que estén habilitadas. La analítica, cuando se acepta, trata direcciones de páginas y datos técnicos de navegación; evita incluir información personal en las URL.'],
      ['Analítica y consentimiento', 'Google Analytics 4 se carga únicamente con permiso. Consent Mode v2 comienza con analytics_storage, ad_storage, ad_user_data y ad_personalization en denied. Solo analytics_storage puede pasar a granted. No están activos Google Ads ni Meta Pixel.'],
      ['Proveedores y destinatarios', 'El sitio se aloja en GitHub Pages. Los formularios utilizan endpoints de Cloudflare Workers. Google recibe datos analíticos solo si los aceptas. Las funciones de cuenta del juego utilizan Supabase cuando están configuradas. Los contratos, subencargados y garantías aplicables a transferencias internacionales deben ser confirmados por el responsable. Los enlaces a Spotify, Instagram y venta de entradas llevan a servicios con sus propias políticas.'],
      ['Conservación', 'La preferencia de cookies se revisa a los 180 días. Los plazos de conservación de consultas, newsletter, cuentas y datos de Analytics deben ser confirmados por el responsable conforme a cada finalidad y obligación aplicable.'],
      ['Derechos', 'Puedes solicitar acceso, rectificación, supresión, oposición, limitación y portabilidad cuando proceda, escribiendo a info@licanevents.com. Si consideras vulnerados tus derechos, puedes reclamar ante la Agencia Española de Protección de Datos (aepd.es).'],
      ['Retirada del consentimiento', 'Puedes cambiar la analítica desde PREFERENCIAS DE COOKIES y retirar el consentimiento de la newsletter a través de su enlace de baja o del correo de contacto. La retirada no afecta al tratamiento lícito anterior.'],
      ['Contacto', 'Para privacidad y ejercicio de derechos: info@licanevents.com. No envíes documentación sensible salvo que resulte necesaria y se te solicite por un canal adecuado.'],
    ],
  },
  cat: {
    notice: 'Informació del lloc en revisió: les dades identificatives completes del responsable i els terminis legals de conservació estan pendents de confirmació. Pots demanar informació a info@licanevents.com.',
    cookies: [
      ['Què són les galetes', 'Són petits fitxers que un lloc desa al navegador. També utilitzem emmagatzematge local per recordar preferències i funcions sol·licitades.'],
      ['Tipus utilitzats', 'Distingim funcions necessàries, analítica opcional i màrqueting. El màrqueting està desactivat i no es carrega cap eina publicitària. Rebutjar és tan senzill com acceptar.'],
      ['Necessàries', 'La tria es desa a lican_cookie_consent i l’idioma a lican-language. El joc pot desar progrés local i dades de sessió si fas servir un compte. Aquestes funcions no depenen del consentiment analític.'],
      ['Analítica i Google Analytics', 'Només després d’acceptar analítiques es carrega Google Analytics 4 (G-C2SPKSH8HJ), de Google. Mesura pàgines, navegació i dades tècniques. El tracker no envia noms, correus ni missatges dels formularis. Consulta també la política de privacitat de Google.'],
      ['Galetes i inventari', 'Verificades després d’acceptar: _ga (distingeix visitants) i _ga_C2SPKSH8HJ (estat de sessió d’Analytics). A Edge la caducitat observada era d’uns 400 dies; pot variar segons navegador i configuració. No es creen abans d’acceptar; les accessibles s’eliminen en retirar el permís.'],
      ['Durada', 'La tria es recorda fins a 180 dies, llevat d’esborrat o canvi de versió. L’emmagatzematge local no caduca sol; el lloc comprova l’antiguitat en carregar. L’idioma i el progrés local romanen fins que es canviïn o esborrin. Els terminis configurats a Analytics estan pendents de confirmació.'],
      ['Canviar o retirar el permís', 'Obre PREFERÈNCIES DE GALETES al peu. Pots retirar analítiques en qualsevol moment. Es bloquegen nous esdeveniments del tracker i s’eliminen les galetes d’Analytics accessibles al lloc. Això no afecta la licitud del tractament anterior.'],
      ['Ajustos del navegador', 'Pots consultar, bloquejar o eliminar galetes i dades als ajustos de privacitat del navegador. Esborrar dades pot eliminar l’idioma, el consentiment o el progrés local.'],
      ['Contacte', 'LICAN EVENTS · Tarragona i Barcelona. Consultes: info@licanevents.com.'],
    ],
    privacy: [
      ['Responsable', 'El lloc es presenta com a LICAN EVENTS, amb activitat a Tarragona i Barcelona. Contacte: info@licanevents.com. La identitat jurídica completa i el domicili del responsable estan pendents de confirmació.'],
      ['Finalitats i base jurídica', 'Gestionem consultes i serveis per atendre la teva petició i, si escau, actuacions precontractuals. La newsletter requereix consentiment específic. L’analítica requereix una tria voluntària separada; rebutjar-la no impedeix utilitzar formularis, newsletter o jocs.'],
      ['Dades tractades', 'El contacte sol·licita nom, correu, tipus de consulta, missatge i confirmació de privacitat. La newsletter sol·licita correu i consentiment. El compte del joc tracta autenticació i les funcions de desament habilitades. L’analítica acceptada tracta adreces de pàgines i dades tècniques; evita posar dades personals a les URL.'],
      ['Analítica i consentiment', 'Google Analytics 4 només es carrega amb permís. Consent Mode v2 comença amb analytics_storage, ad_storage, ad_user_data i ad_personalization en denied. Només analytics_storage pot passar a granted. Google Ads i Meta Pixel no estan actius.'],
      ['Proveïdors i destinataris', 'Allotjament: GitHub Pages. Formularis: endpoints de Cloudflare Workers. Google rep dades analítiques si les acceptes. El compte del joc utilitza Supabase quan està configurat. El responsable ha de confirmar contractes, subencarregats i garanties de transferències internacionals. Spotify, Instagram i venda d’entrades tenen polítiques pròpies.'],
      ['Conservació', 'La preferència de galetes es revisa als 180 dies. Els terminis de consultes, newsletter, comptes i Analytics estan pendents de confirmació segons cada finalitat i obligació aplicable.'],
      ['Drets', 'Pots sol·licitar accés, rectificació, supressió, oposició, limitació i portabilitat quan escaigui a info@licanevents.com. Pots reclamar davant l’Agència Espanyola de Protecció de Dades (aepd.es).'],
      ['Retirada del consentiment', 'Canvia l’analítica a PREFERÈNCIES DE GALETES. Retira el consentiment de la newsletter mitjançant l’enllaç de baixa o el correu de contacte. La retirada no afecta el tractament lícit anterior.'],
      ['Contacte', 'Privacitat i drets: info@licanevents.com. No enviïs documentació sensible tret que sigui necessària i es demani per un canal adequat.'],
    ],
  },
  eng: {
    notice: 'Site information under review: the controller’s full legal identity and statutory retention periods await confirmation. Contact info@licanevents.com for information.',
    cookies: [
      ['What cookies are', 'Cookies are small files stored by a website in your browser. We also use local storage to remember preferences and requested functions.'],
      ['Categories', 'We distinguish necessary functions, optional analytics and marketing. Marketing is disabled; no advertising tools are loaded. Rejecting is as easy as accepting.'],
      ['Necessary storage', 'Your choice is saved in lican_cookie_consent; your language in lican-language. The game may save local progress and session data if you use an account. These functions do not require analytics consent.'],
      ['Analytics and Google Analytics', 'Google Analytics 4 (G-C2SPKSH8HJ), provided by Google, loads only after analytics acceptance. It measures pages, navigation and technical usage data. The tracker does not send names, email addresses or form messages. See Google’s privacy policy too.'],
      ['Cookie inventory', 'Verified after acceptance: _ga (distinguishes visitors) and _ga_C2SPKSH8HJ (Analytics session state). Their observed lifetime in Edge was about 400 days; this may vary by browser and configuration. They are not created before acceptance; accessible cookies are removed on withdrawal.'],
      ['Duration', 'Your choice is remembered for up to 180 days unless deleted or the consent version changes. Local storage has no automatic expiry; the site checks its age on load. Language and local progress remain until changed or deleted. Analytics retention settings await confirmation.'],
      ['Changing or withdrawing consent', 'Open COOKIE PREFERENCES in the footer at any time. Withdrawal blocks new tracker events and removes Analytics cookies accessible to this site. It does not affect the lawfulness of earlier processing.'],
      ['Browser settings', 'You can inspect, block or delete cookies and site data in your browser’s privacy settings. Deletion may remove your language, consent or local game progress.'],
      ['Contact', 'LICAN EVENTS · Tarragona and Barcelona. Contact: info@licanevents.com.'],
    ],
    privacy: [
      ['Controller', 'This site operates under the name LICAN EVENTS, active in Tarragona and Barcelona. Contact: info@licanevents.com. The controller’s full legal identity and address await confirmation.'],
      ['Purposes and legal basis', 'We handle enquiries and service requests to respond to you and, where applicable, take pre-contractual steps. The newsletter requires specific consent. Analytics requires a separate voluntary choice; rejecting it does not prevent forms, newsletter or games from working.'],
      ['Data processed', 'The contact form requests name, email, enquiry type, message and privacy confirmation. The newsletter requests email and consent. Game accounts process authentication data and enabled save functions. Accepted analytics processes page addresses and technical navigation data; avoid personal data in URLs.'],
      ['Web analytics and consent', 'Google Analytics 4 loads only with permission. Consent Mode v2 starts with analytics_storage, ad_storage, ad_user_data and ad_personalization denied. Only analytics_storage can become granted. Google Ads and Meta Pixel are inactive.'],
      ['Providers and recipients', 'Hosting: GitHub Pages. Forms: Cloudflare Workers endpoints. Google receives analytics data only if accepted. Game account functions use Supabase when configured. The controller must confirm contracts, subprocessors and international transfer safeguards. Spotify, Instagram and ticketing links have their own policies.'],
      ['Retention', 'Cookie preferences are reviewed after 180 days. Retention periods for enquiries, newsletters, accounts and Analytics await confirmation for each purpose and applicable obligation.'],
      ['Your rights', 'Where applicable, request access, rectification, erasure, objection, restriction and portability at info@licanevents.com. You may complain to the Spanish Data Protection Agency (aepd.es).'],
      ['Withdrawing consent', 'Change analytics in COOKIE PREFERENCES. Withdraw newsletter consent through its unsubscribe link or our contact email. Withdrawal does not affect earlier lawful processing.'],
      ['Contact', 'Privacy and rights: info@licanevents.com. Do not send sensitive documents unless necessary and requested through an appropriate channel.'],
    ],
  },
  nl: {
    notice: 'Website-informatie wordt herzien: de volledige juridische identiteit van de verantwoordelijke en wettelijke bewaartermijnen moeten nog worden bevestigd. Informatie: info@licanevents.com.',
    cookies: [
      ['Wat zijn cookies?', 'Cookies zijn kleine bestanden die een website in je browser opslaat. We gebruiken ook lokale opslag voor voorkeuren en aangevraagde functies.'],
      ['Categorieën', 'We onderscheiden noodzakelijke functies, optionele analyse en marketing. Marketing is uitgeschakeld; er worden geen reclametools geladen. Weigeren is even eenvoudig als accepteren.'],
      ['Noodzakelijke opslag', 'Je keuze staat in lican_cookie_consent; je taal in lican-language. Het spel kan lokale voortgang en sessiegegevens opslaan als je een account gebruikt. Deze functies vereisen geen analytische toestemming.'],
      ['Analyse en Google Analytics', 'Google Analytics 4 (G-C2SPKSH8HJ) van Google wordt pas na toestemming geladen. Het meet pagina’s, navigatie en technische gebruiksgegevens. De tracker verstuurt geen namen, e-mailadressen of formulierberichten. Zie ook het privacybeleid van Google.'],
      ['Cookie-inventaris', 'Na toestemming geverifieerd: _ga (onderscheidt bezoekers) en _ga_C2SPKSH8HJ (Analytics-sessiestatus). In Edge was de levensduur ongeveer 400 dagen; dit kan per browser en instelling verschillen. Ze ontstaan niet vóór toestemming; toegankelijke cookies worden bij intrekking verwijderd.'],
      ['Duur', 'Je keuze blijft maximaal 180 dagen geldig, tenzij verwijderd of de versie verandert. Lokale opslag verloopt niet vanzelf; de site controleert de ouderdom bij het laden. Taal en spelvoortgang blijven tot wijziging of verwijdering. De bewaartermijnen van Analytics moeten nog worden bevestigd.'],
      ['Toestemming wijzigen of intrekken', 'Open COOKIEVOORKEUREN onderaan de pagina. Intrekken blokkeert nieuwe tracker-events en verwijdert Analytics-cookies die voor de site toegankelijk zijn. Eerdere rechtmatige verwerking blijft onaangetast.'],
      ['Browserinstellingen', 'In de privacyinstellingen van je browser kun je cookies en sitegegevens bekijken, blokkeren en wissen. Wissen kan taal, toestemming of lokale spelvoortgang verwijderen.'],
      ['Contact', 'LICAN EVENTS · Tarragona en Barcelona. Contact: info@licanevents.com.'],
    ],
    privacy: [
      ['Verantwoordelijke', 'Deze site gebruikt de naam LICAN EVENTS en is actief in Tarragona en Barcelona. Contact: info@licanevents.com. De volledige juridische identiteit en het adres moeten nog worden bevestigd.'],
      ['Doelen en rechtsgrond', 'We behandelen vragen en dienstenaanvragen om je verzoek te beantwoorden en zo nodig precontractuele stappen te nemen. De nieuwsbrief vereist specifieke toestemming. Analyse vereist een afzonderlijke vrijwillige keuze; weigeren blokkeert formulieren, nieuwsbrief of spellen niet.'],
      ['Verwerkte gegevens', 'Het contactformulier vraagt naam, e-mail, soort vraag, bericht en privacybevestiging. De nieuwsbrief vraagt e-mail en toestemming. Spelaccounts verwerken authenticatie en ingeschakelde opslagfuncties. Toegestane analyse verwerkt pagina-adressen en technische navigatiegegevens; zet geen persoonsgegevens in URL’s.'],
      ['Analyse en toestemming', 'Google Analytics 4 laadt alleen met toestemming. Consent Mode v2 begint met analytics_storage, ad_storage, ad_user_data en ad_personalization op denied. Alleen analytics_storage kan granted worden. Google Ads en Meta Pixel zijn inactief.'],
      ['Leveranciers en ontvangers', 'Hosting: GitHub Pages. Formulieren: Cloudflare Workers-endpoints. Google ontvangt analysegegevens alleen met toestemming. Spelaccounts gebruiken Supabase indien geconfigureerd. Contracten, subverwerkers en waarborgen voor internationale doorgiften moeten worden bevestigd. Spotify, Instagram en ticketdiensten hanteren eigen beleid.'],
      ['Bewaartermijnen', 'Cookievoorkeuren worden na 180 dagen herzien. Termijnen voor vragen, nieuwsbrief, accounts en Analytics moeten per doel en verplichting worden bevestigd.'],
      ['Rechten', 'Vraag waar van toepassing inzage, correctie, verwijdering, bezwaar, beperking en overdraagbaarheid aan via info@licanevents.com. Je kunt een klacht indienen bij de Spaanse toezichthouder AEPD (aepd.es).'],
      ['Toestemming intrekken', 'Wijzig analyse via COOKIEVOORKEUREN. Trek nieuwsbrief-toestemming in via de afmeldlink of ons e-mailadres. Eerdere rechtmatige verwerking blijft onaangetast.'],
      ['Contact', 'Privacy en rechten: info@licanevents.com. Stuur gevoelige documenten alleen wanneer noodzakelijk en gevraagd via een geschikt kanaal.'],
    ],
  },
  deutsch: {
    notice: 'Die Website-Informationen werden geprüft: vollständige rechtliche Identität des Verantwortlichen und gesetzliche Aufbewahrungsfristen sind noch zu bestätigen. Auskunft: info@licanevents.com.',
    cookies: [
      ['Was sind Cookies?', 'Cookies sind kleine Dateien, die eine Website im Browser speichert. Wir verwenden auch lokalen Speicher für Einstellungen und angeforderte Funktionen.'],
      ['Kategorien', 'Wir unterscheiden notwendige Funktionen, optionale Analyse und Marketing. Marketing ist deaktiviert; Werbetools werden nicht geladen. Ablehnen ist genauso einfach wie Akzeptieren.'],
      ['Notwendiger Speicher', 'Die Auswahl steht in lican_cookie_consent, die Sprache in lican-language. Das Spiel kann lokalen Fortschritt und bei Kontonutzung Sitzungsdaten speichern. Diese Funktionen benötigen keine Analyse-Einwilligung.'],
      ['Analyse und Google Analytics', 'Google Analytics 4 (G-C2SPKSH8HJ) von Google wird erst nach Einwilligung geladen. Es misst Seiten, Navigation und technische Nutzungsdaten. Der Tracker sendet keine Namen, E-Mail-Adressen oder Formularnachrichten. Beachte auch Googles Datenschutzerklärung.'],
      ['Cookie-Inventar', 'Nach Zustimmung geprüft: _ga (unterscheidet Besucher) und _ga_C2SPKSH8HJ (Analytics-Sitzungsstatus). In Edge betrug die beobachtete Laufzeit etwa 400 Tage; Browser und Einstellungen können dies ändern. Vor Zustimmung werden sie nicht erstellt; zugängliche Cookies werden bei Widerruf gelöscht.'],
      ['Dauer', 'Die Auswahl gilt bis zu 180 Tage, sofern sie nicht gelöscht wird oder sich die Version ändert. Lokaler Speicher läuft nicht automatisch ab; die Website prüft das Alter beim Laden. Sprache und Spielfortschritt bleiben bis zur Änderung oder Löschung. Die Analytics-Aufbewahrungsfristen sind noch zu bestätigen.'],
      ['Einwilligung ändern oder widerrufen', 'Öffne COOKIE-EINSTELLUNGEN im Seitenfuß. Ein Widerruf blockiert neue Tracker-Ereignisse und entfernt die für diese Website zugänglichen Analytics-Cookies. Die Rechtmäßigkeit früherer Verarbeitung bleibt unberührt.'],
      ['Browsereinstellungen', 'In den Datenschutzeinstellungen deines Browsers kannst du Cookies und Website-Daten einsehen, blockieren und löschen. Dadurch können Sprache, Einwilligung oder lokaler Spielfortschritt verloren gehen.'],
      ['Kontakt', 'LICAN EVENTS · Tarragona und Barcelona. Kontakt: info@licanevents.com.'],
    ],
    privacy: [
      ['Verantwortlicher', 'Diese Website tritt als LICAN EVENTS auf, tätig in Tarragona und Barcelona. Kontakt: info@licanevents.com. Die vollständige rechtliche Identität und Anschrift sind noch zu bestätigen.'],
      ['Zwecke und Rechtsgrundlagen', 'Wir bearbeiten Anfragen und Dienstleistungswünsche zur Beantwortung und gegebenenfalls für vorvertragliche Maßnahmen. Der Newsletter erfordert gesonderte Einwilligung. Analyse erfordert eine separate freiwillige Wahl; Ablehnen beeinträchtigt Formulare, Newsletter oder Spiele nicht.'],
      ['Verarbeitete Daten', 'Das Kontaktformular erfasst Name, E-Mail, Anfrageart, Nachricht und Datenschutzbestätigung. Der Newsletter erfasst E-Mail und Einwilligung. Spielkonten verarbeiten Authentifizierung und aktivierte Speicherfunktionen. Erlaubte Analyse verarbeitet Seitenadressen und technische Navigationsdaten; vermeide personenbezogene Daten in URLs.'],
      ['Analyse und Einwilligung', 'Google Analytics 4 lädt nur mit Erlaubnis. Consent Mode v2 beginnt mit analytics_storage, ad_storage, ad_user_data und ad_personalization auf denied. Nur analytics_storage kann granted werden. Google Ads und Meta Pixel sind inaktiv.'],
      ['Anbieter und Empfänger', 'Hosting: GitHub Pages. Formulare: Cloudflare-Workers-Endpunkte. Google erhält Analysedaten nur bei Zustimmung. Spielkonten nutzen Supabase, sofern eingerichtet. Verträge, Unterauftragnehmer und Garantien für internationale Übermittlungen sind noch zu bestätigen. Spotify, Instagram und Ticketanbieter haben eigene Richtlinien.'],
      ['Aufbewahrung', 'Cookie-Einstellungen werden nach 180 Tagen überprüft. Fristen für Anfragen, Newsletter, Konten und Analytics sind je Zweck und Verpflichtung noch zu bestätigen.'],
      ['Rechte', 'Soweit anwendbar kannst du Auskunft, Berichtigung, Löschung, Widerspruch, Einschränkung und Datenübertragbarkeit unter info@licanevents.com verlangen. Beschwerden sind bei der spanischen Datenschutzbehörde AEPD (aepd.es) möglich.'],
      ['Widerruf', 'Ändere die Analyse über COOKIE-EINSTELLUNGEN. Die Newsletter-Einwilligung kannst du über den Abmeldelink oder per E-Mail widerrufen. Frühere rechtmäßige Verarbeitung bleibt unberührt.'],
      ['Kontakt', 'Datenschutz und Rechte: info@licanevents.com. Sende sensible Dokumente nur, wenn nötig und über einen geeigneten Kanal angefordert.'],
    ],
  },
  eo: {
    notice: 'La informoj de la retejo estas reviziataj: la plena jura identeco de la respondeculo kaj la laŭleĝaj konservoperiodoj ankoraŭ bezonas konfirmon. Informoj: info@licanevents.com.',
    cookies: [
      ['Kio estas kuketoj?', 'Kuketoj estas malgrandaj dosieroj konservataj de retejo en via retumilo. Ni ankaŭ uzas lokan konservadon por preferoj kaj petataj funkcioj.'],
      ['Kategorioj', 'Ni distingas necesajn funkciojn, laŭvolan analizon kaj merkatadon. Merkatado estas malŝaltita; neniuj reklamaj iloj ŝargiĝas. Rifuzi estas tiel facile kiel akcepti.'],
      ['Necesa konservado', 'Via elekto estas konservata en lican_cookie_consent; la lingvo en lican-language. La ludo povas konservi lokan progreson kaj seancajn datumojn se vi uzas konton. Tiuj funkcioj ne bezonas analizan konsenton.'],
      ['Analizo kaj Google Analytics', 'Google Analytics 4 (G-C2SPKSH8HJ), de Google, ŝargiĝas nur post akcepto de analizo. Ĝi mezuras paĝojn, navigadon kaj teknikajn uzdatumojn. La spurilo ne sendas nomojn, retadresojn aŭ formularajn mesaĝojn. Legu ankaŭ la privatecan politikon de Google.'],
      ['Kuketa inventaro', 'Kontrolitaj post akcepto: _ga (distingas vizitantojn) kaj _ga_C2SPKSH8HJ (seanca stato de Analytics). En Edge la observita daŭro estis ĉirkaŭ 400 tagoj; ĝi povas varii laŭ retumilo kaj agordoj. Ili ne kreiĝas antaŭ akcepto; alireblaj kuketoj foriĝas post retiro.'],
      ['Daŭro', 'La elekto validas ĝis 180 tagoj, krom se forigita aŭ la versio ŝanĝiĝas. Loka konservado ne mem eksvalidiĝas; la retejo kontrolas ĝian aĝon ĉe ŝargo. Lingvo kaj ludprogreso restas ĝis ŝanĝo aŭ forigo. La konservoperiodoj de Analytics ankoraŭ bezonas konfirmon.'],
      ['Ŝanĝi aŭ retiri permeson', 'Malfermu KUKETAJ PREFEROJ ĉe la paĝopiedo. Retiro blokas novajn spurilajn eventojn kaj forigas Analytics-kuketojn alireblajn al la retejo. Ĝi ne ŝanĝas la laŭleĝecon de antaŭa traktado.'],
      ['Retumilaj agordoj', 'Vi povas vidi, bloki aŭ forigi kuketojn kaj retejajn datumojn en la privatecaj agordoj de via retumilo. Forigo povas nuligi lingvon, konsenton aŭ lokan ludprogreson.'],
      ['Kontakto', 'LICAN EVENTS · Tarragona kaj Barcelono. Kontakto: info@licanevents.com.'],
    ],
    privacy: [
      ['Respondeculo', 'La retejo prezentiĝas kiel LICAN EVENTS, aktiva en Tarragona kaj Barcelono. Kontakto: info@licanevents.com. La plena jura identeco kaj adreso de la respondeculo ankoraŭ bezonas konfirmon.'],
      ['Celoj kaj jura bazo', 'Ni traktas demandojn kaj servopetojn por respondi kaj, laŭbezone, fari antaŭkontraktajn paŝojn. La novaĵletero bezonas apartan konsenton. Analizo bezonas apartan libervolan elekton; rifuzo ne malebligas formularojn, novaĵleteron aŭ ludojn.'],
      ['Traktataj datumoj', 'La kontaktformularo petas nomon, retadreson, demandotipon, mesaĝon kaj privatecan konfirmon. La novaĵletero petas retadreson kaj konsenton. Ludkontoj traktas aŭtentikigon kaj aktivigitajn konservajn funkciojn. Akceptita analizo traktas paĝadresojn kaj teknikajn navigajn datumojn; evitu personajn datumojn en URL-oj.'],
      ['Analizo kaj konsento', 'Google Analytics 4 ŝargiĝas nur kun permeso. Consent Mode v2 komenciĝas kun analytics_storage, ad_storage, ad_user_data kaj ad_personalization je denied. Nur analytics_storage povas iĝi granted. Google Ads kaj Meta Pixel estas neaktivaj.'],
      ['Provizantoj kaj ricevantoj', 'Gastigado: GitHub Pages. Formularoj: Cloudflare Workers. Google ricevas analizajn datumojn nur kun akcepto. Ludkontoj uzas Supabase kiam agordite. Kontraktoj, subtraktantoj kaj garantioj pri internaciaj transdonoj bezonas konfirmon. Spotify, Instagram kaj biletservoj havas proprajn politikojn.'],
      ['Konservado', 'Kuketaj preferoj estas reviziataj post 180 tagoj. Periodoj por demandoj, novaĵletero, kontoj kaj Analytics bezonas konfirmon laŭ ĉiu celo kaj aplikebla devo.'],
      ['Rajtoj', 'Laŭ aplikeblo, petu aliron, korektadon, forigon, kontraŭstaron, limigon kaj porteblecon ĉe info@licanevents.com. Vi povas plendi al la hispana datumprotekta aŭtoritato AEPD (aepd.es).'],
      ['Retiro de konsento', 'Ŝanĝu analizon per KUKETAJ PREFEROJ. Retiru novaĵleteran konsenton per la malabonligilo aŭ kontaktretadreso. Retiro ne influas antaŭan laŭleĝan traktadon.'],
      ['Kontakto', 'Privateco kaj rajtoj: info@licanevents.com. Sendu sentemajn dokumentojn nur se necese kaj pete tra taŭga kanalo.'],
    ],
  },
};
